# -*- coding: utf-8 -*-
"""data_training.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13zBt7GYsxdZIeziruRRs-woDMrcUpHqz
"""

### Import Requirements ###
import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from keras.models import Sequential
from keras.layers import Dense, Dropout, Activation, Flatten, Conv1D, MaxPooling1D
from keras.callbacks import EarlyStopping
from tensorflow.keras.optimizers import Adam
import csv
import os
import pickle as pkl
import random




'''
Model Creation
'''

def create_model():

    with tf.device('/GPU:0'):
        CNN_Classifier = Sequential()
        #### FIRST LAYER ####
        CNN_Classifier.add(Conv1D(64,(8), input_shape=(1500,1)))
        CNN_Classifier.add(Activation("relu"))
        CNN_Classifier.add(MaxPooling1D(pool_size = (32)))
        CNN_Classifier.add(Dropout(0.2))

        #### SECOND LAYER ####
        CNN_Classifier.add(Conv1D(128,(4)))
        CNN_Classifier.add(Activation("relu"))
        CNN_Classifier.add(MaxPooling1D(pool_size = (16)))
        CNN_Classifier.add(Dropout(0.2))
        
        #### FINAL LAYER ####
        CNN_Classifier.add(Flatten())
        # CNN_Classifier.add(Dense(64))

        #### OUTPUT LAYER ####
        CNN_Classifier.add(Dense(14))
        CNN_Classifier.add(Activation('softmax'))

    es =  EarlyStopping(monitor='val_loss', mode='min', verbose=1, patience = 10)
    fname = os.path.sep.join(['C:/theCave/ISO-ID/data_prep/weights/',
        "weights-{epoch:03d}-{val_loss:.4f}.hdf5"])


    model_checkpoint_callback = tf.keras.callbacks.ModelCheckpoint(
        fname,
        save_weights_only=True,
        monitor='val_accuracy',
        mode='max',
        save_best_only=True,
        verbose=1)


    with tf.device('/GPU:0'):
        CNN_Classifier.compile(optimizer = tf.keras.optimizers.legacy.Adam(learning_rate = 1e-5, decay = 1e-6),loss = 'categorical_crossentropy', metrics = ['categorical_accuracy', 'accuracy', 'mse'])
    
    return CNN_Classifier,es,model_checkpoint_callback

'''
Data Processing.

- Combines individual isotope csv files to create training csv file and add
a column to label the spectrum.

- From consolidated csv file split the data set to traininf and validation
set.
'''
label_name = ['Cr51', 'Co57', 'F18', 'Co60', 'Xe133', 'I123', 'In111', 'I125',
       'Sm153', 'Ir192', 'I131', 'Se75', 'Cs137', 'Ga67']
label_number = [ 2  ,0  ,4  ,1 ,13  ,6  ,9  ,7 ,12 ,10  ,8 ,11 ,3 ,5]




#Function to create consolidated dataset
def consolidated_data(folder_path, output_file):
    # create the header for the output file
    header_written = False
    count = 1
    with open(output_file, 'w', newline='') as f_out:
        csv_writer = csv.writer(f_out)

        for filename in os.listdir(folder_path):
            if filename.endswith(".csv") and filename != output_file:
                with open(os.path.join(folder_path, filename), 'r') as f_in:
                    csv_reader = csv.reader(f_in)
                    for row in csv_reader:
                        label = filename.split()[0]
                        row.append(label)
                        csv_writer.writerow(row)
                        count = count + 1


#Function to create consolidated dataset for pickle files

def consolidated_data_pkl(folder_path, output_file):
    count = 0
    with open(output_file, 'w', newline='') as f_out:
        csv_writer = csv.writer(f_out)

        for filename in os.listdir(folder_path):
            if filename.endswith(".pkl") and filename != output_file:
                with open(os.path.join(folder_path, filename), 'rb') as f_in:
                    data = pkl.load(f_in)
                    name_col = np.full((data.shape[0],1),label_number[label_name.index(filename.split('.')[0])])
                    data_with_name = np.concatenate((data,name_col),axis=1)
                    csv_writer.writerows(data_with_name)




#Function to splitting the dataset to training and validation set.
#input : consolidated csv file containing all spectrum with labels
def split_dataset(input_file):           
    line_offsets = list()
    with open(input_file,'r') as f:
        title = f.readline()
        # store offset of the first
        while True:
            # store offset of the next line start
            line_offsets.append(f.tell())
            line = f.readline()
            if line=="":
                break

        # now shuffle the offsets
        random.shuffle(line_offsets)
        print("len :", len(line_offsets))

        # and write the output file
        with open("train_select.csv", 'w') as fw:
            fw.write(title)
            for offset in line_offsets[0:int(0.8*len(line_offsets))]: #for offset in line_offsets[x*0.8]:
                
                f.seek(offset)
                fw.write(f.readline())

        with open("validation_select.csv", 'w') as fw:
            for offset in line_offsets[int(0.8*len(line_offsets)):-1]: 
                
                f.seek(offset)
                fw.write(f.readline())



'''
Data training : 
- Create mechanism to deal with large dataset. 
- Train and test model.
'''

#Function to read large csv file. To be used to model's generator function for training.
def read_csv(filename):
    with open(filename, 'r') as f:
        reader = csv.reader(f)
        count = 0

        glob_labels  = []
        glob_features = []
        for line in reader:
            # print('line : ' ,line)
            if count == 1 : 
                glob_features = []
                glob_labels = []
        # record = line.rstrip().split(',').astype(int)
            features = [int(float(n)) for n in line[:1500]]
            label = line[-1]
            features = np.array(features)
            features = features.reshape(1500,-1)
  
            yield features, tf.keras.utils.to_categorical(int(label), num_classes=14)



def main():


    folder_path = 'C:/theCave/ISO-ID/data_prep/output_data/single_isotope_data'
    output_file = 'C:/theCave/ISO-ID/data_prep/output_data/single_isotope_data/output.csv'
    #Merge data
    # consolidated_data_pkl(folder_path, output_file)
    print("....Finished merging dataset......")

    #Split data
    # split_dataset(output_file)
    print("....Finished splitting dataset......")

    #Read training dataset
    tf_ds = lambda: read_csv('C:/theCave/ISO-ID/data_prep/output_data/single_isotope_data/train_select.csv')

    #Create Dataset using dataset generator 
    dataset = tf.data.Dataset.from_generator(tf_ds,output_signature=(tf.TensorSpec(shape=(1500,1), dtype=tf.uint16),tf.TensorSpec(shape=([14]), dtype=tf.uint8)))

    dataset = dataset.shuffle(1000)
    dataset = dataset.batch(256).prefetch(3)

    #Read Validation dataset
    val_ds = lambda: read_csv('C:/theCave/ISO-ID/data_prep/output_data/single_isotope_data/validation_select.csv')
    val_ds = tf.data.Dataset.from_generator(val_ds, output_types = (tf.float32, tf.int64), output_shapes = (tf.TensorShape([1500,1]),tf.TensorShape([14])))

    val_ds = val_ds.batch(256).prefetch(3)
    model,es,model_checkpoint_callback = create_model()
    history = model.fit(dataset,validation_data = val_ds ,epochs = 100, callbacks = [es , model_checkpoint_callback], verbose=2)

    print("Training finished")

if __name__ == "__main__":
    main()